const CLASSES = [
  {
    title: "6",
    name: "Class 6",
    desc: "Building strong foundations in mathematics and language arts while introducing scientific concepts.",
    img: "https://lh3.googleusercontent.com/aida-public/AB6AXuAjzTlvpUgh072Emzi221HZkOGFWRfIVdYm-n9mJMux1tm3YHL1llbXqdlgAWW5p66o7-b8fyN7cSZAfk1_Az9ujQ3lp9TDcugl1z8SEcbQ9Bw3qIS7nhHXQ-VowxJFDvNrp5ed5BhDAGAdwqBYhyDznOa4Mm6HxNAYviVrsEpLDmJB11hD5SY155RtGODd1CWnaU4ZFtW1FM2pP4syIzk1Gko8yfD8Vwv2cPrCgYzcxU0zBrrNhKIoOu2o2EM8jiYTbpEqEUCl5701",
    alt: "Students in a classroom setting",
    badge: "Junior Section",
    badgeBg: "bg-[#3F72AF]",
    tagLabel: "Core Subjects",
    tags: ["Bengali", "English", "Math", "Science", "ICT"],
    tagStyle: "bg-gray-100 text-gray-700",
  },
  {
    title: "7",
    name: "Class 7",
    desc: "Expanding knowledge horizons with intermediate algebra and introduction to global history.",
    img: "https://lh3.googleusercontent.com/aida-public/AB6AXuAik_cRQZe3DXwSLTvfaOu-wND_5vsaNV2QtSSkvhU4LZIy9D9_tpcfW77oWwetof6Cil_6gC0Ns6OIEUBKPxfuR2OaySgAdeI0zqEGIwOyHOe5qcQlKVGaleKgEu2k4bYp-8TvewePoOVpM3qa4N8O1ARqvTm0yVBZHvwjMAj0TS8j3ZKg8TVALBYN9kshJ1DBlrK1rr__ivanKjXLpa76NKVXcnubxQLfI6KXfV0azIZj0RFfFdzkPHBqW9wfGYMlZ95QER3QHwgg",
    alt: "Students using tablets",
    badge: "Junior Section",
    badgeBg: "bg-[#3F72AF]",
    tagLabel: "Core Subjects",
    tags: ["Bengali", "English", "Algebra", "Biology", "History"],
    tagStyle: "bg-gray-100 text-gray-700",
  },
  {
    title: "8",
    name: "Class 8",
    desc: "Preparing for JSC examinations with focused curriculum on analytical skills and composition.",
    img: "https://lh3.googleusercontent.com/aida-public/AB6AXuBlQ_bC0S7TqEUU0aN0xXMKxrg0fQ4tlUYg3BxMzZ9neXqG_HidiZCg8aYhLt9V1xRECOvFgH9AWzc-TbZfyWNCqbsDpBatuIHNi5tEnaZ3N2ju95SlrYi24HAFQWhZwZAUa4pBKuKDTo8Q3qMgYgc5p7Qch5wFGRFZByrLP1R966B6X19LxOV0e-DdyqvGkHtuZBZtH0Ax_W_CfiF44fxs7SZP7S3WyO4W1q0O3yB3t7coMnDjqMOKl1ZYPd8s1KYlmsSmCz9jaFYv",
    alt: "Library study session",
    badge: "Junior Section",
    badgeBg: "bg-[#3F72AF]",
    tagLabel: "Core Subjects",
    tags: ["Geometry", "English Lit", "Physics", "Chemistry", "Art"],
    tagStyle: "bg-gray-100 text-gray-700",
  },
  {
    title: "9",
    name: "Class 9",
    desc: "Stream selection (Science, Commerce, Arts) and advanced curriculum introduction.",
    img: "https://lh3.googleusercontent.com/aida-public/AB6AXuAam1_vGgOz4daS0nG89HDGX2BPEI4RJUx_zBnCAbGWIyFfd_1o0QxkLAJxCJjt7AQ62ywjrir7Ul3QcV8LhtOpSVaF4bTwQd9wwSX9QsdKmDdxDLMjf_8uYLKuPE64qdWgp_Yxey2-d2vPGBTevYZHZO14PRIvYXWxpc2bFSpImZjUNOecR5BrYQz-CGLu1sDLga5e3-ckKITTl2yrRCiGuP9UtEl0sxiwzFZojNbPrIQnlkk3NT3iYziYzSRoTsIGNyFz4cI7zFQ8",
    alt: "Students discussing a project",
    badge: "Senior Section",
    badgeBg: "bg-[#112D4E]",
    tagLabel: "Available Streams",
    tags: ["Science", "Commerce", "Arts"],
    tagStyle: "bg-blue-50 text-[#3F72AF] border border-blue-100",
  },
  {
    title: "10",
    name: "Class 10",
    desc: "Intensive preparation for SSC examinations with mock tests and personalized guidance.",
    img: "https://lh3.googleusercontent.com/aida-public/AB6AXuCGywAEWMUjLv0cPhdAQ6nQNpOV3XocvvOL8eraCj8UF0z9LXIjVKLnEOEpo7eFb0TX6w8G6GiCRuQ7edUJKh5XsmvpIgO-XSW3-jeU1TetUhzQbVsM1v97uCuOFhQYSBg8zYlIlO2Oh-aAkILVWFFbcj9P6GnRXrgs63xY6G_y2HyRAT5Efgln93f5ITFAot7eUGEdkZOFcvcLidHWFxghUw2Hw0dImMHBltMc1Y39oVNoLhTWp_GXAhGkJUjF8tg8UXYPaYDE39l9",
    alt: "Group study",
    badge: "Senior Section",
    badgeBg: "bg-[#112D4E]",
    tagLabel: "Focus Areas",
    tags: ["SSC Prep", "Model Tests", "Career Guidance"],
    tagStyle: "bg-orange-50 text-orange-600 border border-orange-100",
  },
];

export { CLASSES };
